language: csharp

os:
 - linux

dist: bionic
mono: none
dotnet: 3.0.100

env:
  - TEST_SUITE="without-cultures"
  - TEST_SUITE="cultures"

install:
  - dotnet tool install -g dotnet-format
  - export PATH="$PATH:$HOME/.dotnet/tools"
  - dotnet-format --version
script: |
  echo "Checking format..." 
  dotnet format --check --dry-run -w . -v diagnostic # check C# formatting for neo.sln
  cd neo.UnitTests
  if [[ "$TEST_SUITE" == "cultures" ]]; then
      dotnet test -v m --filter FullyQualifiedName=Neo.UnitTests.UT_Culture.All_Tests_Cultures
  else
      if [[ "$TEST_SUITE" == "without-cultures" ]]; then
        # Test & Calculate coverage
        find * -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
        dotnet test -v m --filter FullyQualifiedName!=Neo.UnitTests.UT_Culture.All_Tests_Cultures /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      else
        # Only test
        dotnet test -v m --filter FullyQualifiedName!=Neo.UnitTests.UT_Culture.All_Tests_Cultures
      fi
  fi
after_success: |
  if [[ "$TEST_SUITE" == "without-cultures" ]]; then
    # Send coverage
    echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
    bash <(curl -s https://codecov.io/bash) -v
  fi


